= Spring Asciidoctor Extensions

== Using the extensions

The extensions are published to the https://repo.spring.io/release Maven repository.
They can be used by adding a dependency to your Maven or Gradle build:

=== Gradle

Add a dependency on the extensions to the `asciidoctor` configuration:

----
repositories {
    maven { url "https://repo.spring.io/release"  }
}
...
asciidoctor 'io.spring.asciidoctor:spring-asciidoctor-extensions:<<version>>'
----

=== Maven

Add a dependency to your existing configuration of the `asciidoctor-maven-plugin`:

----
...
  <repositories>
    <repository>
      <id>springiorelease</id>
      <name>spring io release</name>
      <url>https://repo.spring.io/release</url>
    </repository>
    ...
  </repositories>
...    
<plugin>
	<groupId>org.asciidoctor</groupId>
	<artifactId>asciidoctor-maven-plugin</artifactId>
	<dependencies>
		<dependency>
			<groupId>io.spring.asciidoctor</groupId>
			<artifactId>spring-asciidoctor-extensions</artifactId>
			<version><<version>></version>
		</dependency>
	</dependencies>
</plugin>
----

The list of available versions can be directly obtained from hte repository: https://repo.spring.io/release/io/spring/asciidoctor/spring-asciidoctor-extensions/

== Available extensions

=== Code block switch

Post-processes Asciidoctor's HTML output to collapse multiple code blocks into one and provides
tabs that can be used to switch between them. Requires one block that has a `role="primary"`
attribute and one or more blocks that have a `role="secondary"` attribute. The tabs are named using
the block titles.

For example:

[source,indent=0]
....
[source,xml,indent=0,role="primary"]
.Maven
----
<dependency>
    <groupId>com.example</groupId>
    <artifactId>some-library</artifactId>
    <version>1.2.3</version>
</dependency>
----

[source,indent=0,role="secondary"]
.Gradle
----
compile 'com.example:some-library:1.2.3
----
....
