:version: 0.1.3.RELEASE

= Spring Asciidoctor Extensions

== Using the extensions

The extensions are published to the https://repo.spring.io/release Maven repository.
They can be used by adding a dependency to your Maven or Gradle build:

=== Gradle

Make the Spring release repository available to your build:

[source,groovy,subs="verbatim,attributes"]
----
repositories {
    maven { url "https://repo.spring.io/release"  }
}
----

Add a dependency on the extensions to the `asciidoctor` configuration:

[source,groovy,subs="verbatim,attributes"]
----
dependencies {
    asciidoctor 'io.spring.asciidoctor:spring-asciidoctor-extensions:{version}'
}
----

=== Maven

Make the Spring release repository available to your build:

[source,xml,subs="verbatim,attributes"]
----
<repositories>
    <repository>
        <id>spring-release</id>
        <name>Spring Release</name>
        <url>https://repo.spring.io/release</url>
    </repository>
</repositories>
----

Add a dependency to your existing configuration of the `asciidoctor-maven-plugin`:

[source,xml,subs="verbatim,attributes"]
----
<plugin>
	<groupId>org.asciidoctor</groupId>
	<artifactId>asciidoctor-maven-plugin</artifactId>
	<dependencies>
		<dependency>
			<groupId>io.spring.asciidoctor</groupId>
			<artifactId>spring-asciidoctor-extensions</artifactId>
			<version>{version}</version>
		</dependency>
	</dependencies>
</plugin>
----

== Available extensions

=== Code block switch

Post-processes Asciidoctor's HTML output to collapse multiple code blocks into one and provides
tabs that can be used to switch between them. Requires one block that has a `role="primary"`
attribute and one or more blocks that have a `role="secondary"` attribute. The tabs are named using
the block titles.

For example:

[source,subs="verbatim,attributes"]
....
[source,xml,indent=0,role="primary"]
.Maven
----
<dependency>
    <groupId>com.example</groupId>
    <artifactId>some-library</artifactId>
    <version>1.2.3</version>
</dependency>
----

[source,indent=0,role="secondary"]
.Gradle
----
compile 'com.example:some-library:1.2.3
----
....
